version: '3'
services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: test
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    zxcvbn:
        image: wcjr/zxcvbn-api:1.1.0
        ports:
            - "3000"

    app:
        build: .
        depends_on:
            - db
            - zxcvbn
            - broker
            - ldapload
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: test
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt
            ALERTS_EMAIL_ENABLED: "false"
            ALERTS_EMAIL: alerts@nowhere.com
            ID_BROKER_baseUrl: http://broker
            ID_BROKER_accessToken: abc123
            ID_BROKER_assertValidBrokerIp: "false"
            ID_BROKER_validIpRanges: 127.0.0.1/32,192.168.65.1/32
            TEST_GOOGLE_PWSTORE_CONFIG_applicationName: idpGooglePwStoreTestsByCI
            RECAPTCHA_REQUIRED: "false"
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            EMAILER_CLASS: tests\mock\emailer\FakeEmailer
            AUTH_CLASS: tests\mock\auth\Component
            PASSWORDSTORE_CLASS: tests\mock\passwordstore\Component
            ZXCVBN_API_BASEURL: http://zxcvbn:3000
            PASSWORD_RULE_minLength: 10
            PASSWORD_RULE_maxLength: 255
            PASSWORD_RULE_minScore: 2
        working_dir: /data
        command: /data/run-tests.sh

    brokerDb:
        image: mariadb:10
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass

    broker:
        image: silintl/idp-id-broker:develop
        depends_on:
            - brokerDb
        volumes:
            - ./dockerbuild/broker/run-broker.sh:/data/run-broker.sh
            - ./dockerbuild/broker/m381901_235959_insert_test_data.php:/data/console/migrations/m381901_235959_insert_test_data.php
            - ./dockerbuild/broker/User.php:/data/console/migrations/User.php
            - ./dockerbuild/broker/Method.php:/data/console/migrations/Method.php
        environment:
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: idp1
            MYSQL_HOST: brokerDb
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            API_ACCESS_KEYS: abc123
            HELP_CENTER_URL: https://example.com/#/help
            PASSWORD_FORGOT_URL: https://example.com/#/forgot
            PASSWORD_PROFILE_URL: https://example.com/#/profile
            SUPPORT_EMAIL: support@example.com
            EMAIL_SIGNATURE: Dummy Signature for Tests
            APP_ENV: test
            MFA_TOTP_apiBaseUrl: not_needed_here
            MFA_TOTP_apiKey: not_needed_here
            MFA_TOTP_apiSecret: not_needed_here
            MFA_WEBAUTHN_apiBaseUrl: not_needed_here
            MFA_WEBAUTHN_apiKey: not_needed_here
            MFA_WEBAUTHN_apiSecret: not_needed_here
        command: ./run-broker.sh

    ldap:
        build: ./dockerbuild/ldap
        environment:
            DEBUG_LEVEL: 320

    ldapload:
        build: ./dockerbuild/ldap
        depends_on:
            - ldap
        working_dir: /data
        command: ./load_ldap.sh
