version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: pwmgr
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    testDb:
       image: silintl/mariadb:latest
       environment:
           MYSQL_ROOT_PASSWORD: r00tp@ss!
           MYSQL_DATABASE: test
           MYSQL_USER: idpmgmt
           MYSQL_PASSWORD: idpmgmt

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "51151:80"
        environment:
            PMA_HOST: db
            PMA_USER: idpmgmt
            PMA_PASSWORD: idpmgmt

    api:
        build: ./
        volumes_from:
            - data
        ports:
            - "51155:80"
        depends_on:
            - db
            - email
            - memcache1
            - memcache2
        env_file:
            - ./common.env
            - ./local.env

    apitest:
        build: ./
        volumes_from:
            - data
        depends_on:
            - testDb
            - zxcvbn
            - broker
        env_file:
            - ./common.env
            - ./test.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
            ID_BROKER_baseUrl: http://broker
        command: ["/data/run-tests-api.sh"]

    unittest:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        depends_on:
            - testDb
            - zxcvbn
            - memcache1
            - memcache2
        env_file:
            - ./common.env
            - ./test.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
            ID_BROKER_baseUrl: http://broker
            MEMCACHE_CONFIG1_host: memcache1
            MEMCACHE_CONFIG1_port: 11211
            MEMCACHE_CONFIG1_weight: 100
            MEMCACHE_CONFIG2_host: memcache2
            MEMCACHE_CONFIG2_port: 11211
            MEMCACHE_CONFIG2_weight: 50
        command: ["/data/run-tests.sh"]

    integrationtest:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        depends_on:
            - testDb
            - zxcvbn
            - memcache1
            - memcache2
        env_file:
            - ./common.env
            - ./test.env
            - ./local.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
            ID_BROKER_baseUrl: http://broker
            MEMCACHE_CONFIG1_host: memcache1
            MEMCACHE_CONFIG1_port: 11211
            MEMCACHE_CONFIG1_weight: 100
            MEMCACHE_CONFIG2_host: memcache2
            MEMCACHE_CONFIG2_port: 11211
            MEMCACHE_CONFIG2_weight: 50
        command: ["/data/run-tests-integration.sh"]

    cli:
        build: ./
        volumes_from:
            - data
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        working_dir: /data
        user: "${DOCKER_UIDGID}"
        env_file:
            - ./common.env
            - ./local.env
        command: ["true"]

    email:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
            - emailcron
        env_file:
            - ./email.common.env
            - ./email.local.env
        ports:
            - "51153:80"

    emailcron:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
        env_file:
            - ./email.common.env
            - ./email.local.env
        command: /data/run-cron.sh

    emaildb:
        image: silintl/mariadb:latest
        env_file:
            - ./email.common.env
        environment:
            MYSQL_ROOT_PASSWORD: not-a-secret

    emailpma:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "51152:80"
        environment:
            PMA_HOST: emaildb
            PMA_USER: email
            PMA_PASSWORD: email

    zxcvbn:
        image: wcjr/zxcvbn-api:1.1.0

    brokerDb:
        image: silintl/mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker

    brokerpma:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "51158:80"
        environment:
            PMA_HOST: brokerDb
            PMA_USER: broker
            PMA_PASSWORD: broker

    broker:
        image: silintl/idp-id-broker:develop
        ports:
            - "51154:80"
        depends_on:
            - brokerDb
        volumes:
            - ./dockerbuild/broker/run-broker.sh:/data/run-broker.sh
            - ./dockerbuild/broker/m381901_235959_insert_test_data.php:/data/console/migrations/m381901_235959_insert_test_data.php
            - ./dockerbuild/broker/User.php:/data/console/migrations/User.php
            - ./dockerbuild/broker/Method.php:/data/console/migrations/Method.php
        environment:
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: idp1
            MYSQL_HOST: brokerDb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            API_ACCESS_KEYS: abc123
            HELP_CENTER_URL: https://example.com/#/help
            PASSWORD_FORGOT_URL: https://example.com/#/forgot
            PASSWORD_PROFILE_URL: https://example.com/#/profile
            SUPPORT_EMAIL: support@example.com
            EMAIL_SIGNATURE: Dummy Signature for Tests
            APP_ENV: test
        command: ./run-broker.sh

    ldap:
        build: ./dockerbuild/ldap

    ldapload:
        build: ./dockerbuild/ldap
        depends_on:
            - ldap
        working_dir: /data
        command: ./load_ldap.sh

    raml2html:
        image: mattjtodd/raml2html
        volumes:
            - ./api.raml:/api.raml
            - ./api.html:/api.html
        command: -i api.raml -o api.html

    memcache1:
        image: memcached:1.4-alpine
        ports:
            - "11211"

    memcache2:
        image: memcached:1.4-alpine
        ports:
            - "11211"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.31.0/24
              gateway: 10.20.31.1

