<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '접근 토큰',
    'Access Token Expiration' => '액세스 토큰 만료',
    'Auth Type' => '인증 유형',
    'Created' => '생성됨',
    'Display Name' => '표시 이름',
    'Email' => '이메일',
    'Employee ID' => '직원 식별',
    'First Name' => '이름',
    'ID' => '아이디',
    'Idp Username' => 'IdP 사용자 이름',
    'Last Name' => '성',
    'Uuid' => 'UUID',
];
